name: Linux build
on: [push, pull_request]
concurrency:
  group: ${{ github.workflow }}-${{ github.job }}-${{ github.ref }}
  cancel-in-progress: true
defaults:
  run:
    shell: bash -l {0}
jobs:
  build:
    runs-on: ubuntu-latest
    name: '${{ matrix.sys.compiler }} / ${{ matrix.flags.cxxflags }}'
    strategy:
      matrix:
        sys:
          - { compiler: 'g++'}
          - { compiler: 'clang++'}
        flags:
          - { cxxflags: '-O2' }
          - { cxxflags: '-O0 -g -fsanitize=address' }
    steps:
    - name: Setup GCC
      if: ${{ matrix.sys.compiler == 'g++' }}
      run: |
        sudo apt-get update
        sudo apt-get --no-install-suggests --no-install-recommends install g++-arm-linux-gnueabihf qemu-user
        sudo apt-get --no-install-suggests --no-install-recommends install g++-aarch64-linux-gnu qemu-user
    - name: Setup Clang
      if: ${{ matrix.sys.compiler == 'clang++' }}
      run: |
        sudo apt-get update
        sudo apt-get --no-install-suggests --no-install-recommends install g++-arm-linux-gnueabihf qemu-user
        sudo apt-get --no-install-suggests --no-install-recommends install g++-aarch64-linux-gnu qemu-user
    - name: Checkout gemmology
      uses: actions/checkout@v3
    - name: Checkout xsimd
      uses: actions/checkout@v3
      with:
        repository: QuantStack/xsimd
        path: xsimd
    - name: Setup SDE
      run: sh .github/workflows/install_sde.sh

    - name: Check GCC
      if: ${{ matrix.sys.compiler == 'g++' }}
      run: make -C test CXX=${{ matrix.sys.compiler }} "CXXFLAGS=-Wall -Wno-psabi -Wno-unused-result -Werror ${{ matrix.flags.cxxflags }}" SDE64=../sde-external-9.21.1-2023-04-24-lin/sde64 XSIMD_INCLUDE_DIR=../xsimd/include -j ARM_CXX=arm-linux-gnueabihf-g++ ARM_QEMU=qemu-arm\ -L\ /usr/arm-linux-gnueabihf ARM64_CXX=aarch64-linux-gnu-g++ ARM64_QEMU=qemu-aarch64\ -L\ /usr/aarch64-linux-gnu

    - name: Check Clang
      if: ${{ matrix.sys.compiler == 'clang++' }}
      run: make -C test CXX=${{ matrix.sys.compiler }} "CXXFLAGS=-Wall -Wno-psabi -Wno-unused-result -Werror ${{ matrix.flags.cxxflags }}" SDE64=../sde-external-9.21.1-2023-04-24-lin/sde64 XSIMD_INCLUDE_DIR=../xsimd/include -j NOOMP=1
